### ISSUE TITLE
Configuration options need to be quoted

### ISSUE THREAD

**Issue by marcoceppi** [cloud-benchmarks/benchmark-gui#1]
In this bundle, http://cloud-benchmarks.org/submissions/17.yaml the URL isn't quoted, which will anger YAML parsers because of the double `:`. All configuration keys should be quoted.

**Comment by tvansteenburgh** [comment]
As it turns out, this was a red herring. The real problem was that bundle constraints need to be a string, not a dict (at least until juju-deployer supports the latter). Fixed in 435a78122fd420aea07cae66324be77cae0b15ea
